# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='iban_number',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='paypal_account',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='fund_raiser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='fundraiser.FundRaiser'),
            preserve_default=False,
        ),
    ]
