# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0002_auto_20160528_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
    ]
