# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0002_projectindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='teaser',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
