# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0005_pledgeformfield_pledgeformpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_nr', models.TextField()),
                ('billing_name', models.CharField(blank=True, max_length=250)),
                ('billing_company', models.CharField(blank=True, max_length=250)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_date', models.DateField(auto_now_add=True)),
                ('paid_date', models.DateField(editable=False)),
                ('paid_issuer', models.CharField(editable=False, max_length=250)),
                ('paid_id', models.CharField(editable=False, max_length=250)),
                ('anonymous', models.BooleanField(default=False)),
                ('amount', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundraiser.ProjectPage')),
            ],
        ),
    ]
