# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='fundraiser.ProjectPage'),
        ),
    ]
