# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.wagtailroutablepage.models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('fundraiser', '0008_auto_20160809_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('submit_info', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('thanks_info', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.wagtailroutablepage.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='prize',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
