# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('fundraiser', '0009_auto_20160809_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledgeformfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pledgeformpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='PledgeFormField',
        ),
        migrations.DeleteModel(
            name='PledgeFormPage',
        ),
    ]
