# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0011_auto_20160809_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='show_comments',
            field=models.BooleanField(default=True),
        ),
    ]
