# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0014_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_date',
            field=models.DateField(blank=True, editable=False),
        ),
    ]
