# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0015_auto_20160826_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
