# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0016_auto_20160826_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='amount',
            new_name='amount_needed',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='amount_raised',
            field=models.IntegerField(default=0),
        ),
    ]
