# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160716_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='show_comments',
            field=models.BooleanField(default=True),
        ),
    ]
