# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-09 22:24
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_staticpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='extra_content',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
